<a href="https://colab.research.google.com/github/sanjay-agalave/google-colab-notebook/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**NumPy**

## **What is NumPy?**
*   NumPy is a Python library used to work with arrays (data stored in a list-like structure).
*   It also provides tools for mathematics, linear algebra, and matrix operations.

## **Why Use NumPy?**
*   Python lists can act like arrays, but they are slow.
*   NumPy arrays are much faster.

## **Why is NumPy Faster Than Lists?**
*   NumPy stores data in continuous memory, so it is quicker to access and modify.
*   Python lists store elements in different memory locations, which slows things down.
*   NumPy uses C/C++ code internally, making calculations very fast.

## Create a NumPy ndarray Object
*   The array object in NumPy is called ndarray. We can create a NumPy ***ndarray*** object by using the ***array()*** function.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


*   To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:



In [ ]:
#Used tuple to create array
arr = np.array((2, 3, 4, 5, 1))
print(arr)
print(type(arr))

[2 3 4 5 1]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


## **NumPy Array Indexing**

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4])

5


In [ ]:
print(arr[2] + arr[3])

7


In [ ]:
print(arr[6] - arr[1])

5


In [ ]:
print(arr[7])

IndexError: index 7 is out of bounds for axis 0 with size 7

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])

In [ ]:
print(arr[0,0])

1


In [ ]:
print(arr[1,2])

8


In [ ]:
print(arr[1, 4])

0


In [ ]:
arr = np.array([[[1, 2, 3,], [4, 5, 6], [7, 8, 9]], [[12, 11, 13], [14, 15, 16], [17, 18, 19]], [[21, 22, 23], [24, 25, 26], [27, 28, 29]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[12 11 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [ ]:
print(arr[1, 0, 1])

11


In [ ]:
print(arr[2, 2, 1])

28


In [ ]:
print(arr[0, 2, 1])

8


In [ ]:
print(arr[-1, -1, 2])

29


In [ ]:
print(arr[-3, -2, 0])

4


## **NumPy Array Slicing**


*   Slicing in python means taking elements from one given index to another given index.

*   we pass slice instead of index like this: **[start:end].**
*   We can also define the step, like this: **[start:end:step]**